
version: '3'
services:
  kong:
    image: kong
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8443:8443"
      - "8444:8444"
    depends_on:
      - postgres
    links:
      - postgres
      - app
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=postgres
      - KONG_LOG_LEVEL=info
      - KONG_ADMIN_LISTEN=0.0.0.0:8001, 0.0.0.0:8444 ssl
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr

  postgres:
    image: postgres:9.6
    ports:
      - "5432:5432"
    volumes:
      - "./data:/var/lib/postgresql/data"
    environment:
      - POSTGRES_USER=kong
      - POSTGRES_DB=kong

  konga:
    image: pantsel/konga
    ports:
      - "1337:1337"
    links:
      - kong
      - postgres
    depends_on:
      - kong
    environment:
      - NODE_ENV=production
      - TOKEN_SECRET=C6cSgh6D76ZtaKqAf9yFyuzvXiC289qj

  app:
    image: lealssa/python-app-hml
    volumes:
      - "./app:/usr/src/app"
    entrypoint: python /usr/src/app/app.py
